### ISSUE TITLE
ISA & ABI for chili

### ISSUE THREAD

**Issue by parthitce** [nkim-bitzap/chili-gcc-8.4#1]
Thank you very much for the wonderful effort in creating the understanding for gcc backend port.

Questoin:

- Do we have standard ISA and ABI document for this architecture?

**Comment by nkim-bitzap** [comment]
You are welcome, happy to help.
I have just committed all Chili docs i still have to the source/docs directory.

This is not much, unfortunately all hardware specs and docs are gone forever
